package com.example.tasktracker.model

data class Task(
    val id: Long = 0, // Will be auto-generated by Room in the Entity
    val title: String,
    val description: String?,
    val isCompleted: Boolean = false,
    val createdAt: Long = System.currentTimeMillis() // Using Long for timestamp
)